"""Board projections: ``plans/STATUS.md`` and ``plans/status.json``.

Both files are regenerated wholesale on every transition and are never edited
by hand — the column folders remain the sole ground truth (D8).  Titles come
from frontmatter, never from splitting filenames on ``-`` (a v3 defect that
broke on slugs containing digits).
"""

from __future__ import annotations

import json
from collections.abc import Iterable, Mapping, Sequence
from datetime import datetime
from pathlib import Path

FIELDS = ("id", "title", "status", "owner", "branch", "worktree", "updated", "column")

Record = Mapping[str, str]


def _sort_key(record: Record) -> tuple[str, int, str]:
    """Deterministic order: prefix, then numeric id, then raw id."""
    ticket_id = record.get("id", "")
    prefix, _, number = ticket_id.rpartition("-")
    try:
        numeric = int(number)
    except ValueError:
        numeric = 0
    return (prefix, numeric, ticket_id)


def _grouped(
    records: Iterable[Record], columns: Sequence[str]
) -> dict[str, list[Record]]:
    grouped: dict[str, list[Record]] = {column: [] for column in columns}
    for record in records:
        grouped.setdefault(record.get("column", ""), []).append(record)
    for bucket in grouped.values():
        bucket.sort(key=_sort_key)
    return grouped


def _escape_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ").strip()


def render_markdown(
    records: Iterable[Record],
    columns: Sequence[str],
    *,
    timestamp: datetime,
    project_name: str = "",
) -> str:
    grouped = _grouped(records, columns)
    heading = f"# Board Status{f' — {project_name}' if project_name else ''}"
    lines = [
        heading,
        "",
        "<!-- GENERATED BY kahnban. Do not edit; run `kahnban sync`. -->",
        "",
        f"Generated: {timestamp.strftime('%Y-%m-%d %H:%M')}",
        "",
        "## Column counts",
        "",
        "| Column | Tickets |",
        "| :--- | ---: |",
    ]
    for column in columns:
        lines.append(f"| {column} | {len(grouped.get(column, []))} |")
    lines.append("")

    for column in columns:
        bucket = grouped.get(column, [])
        lines.extend([f"## {column} ({len(bucket)})", ""])
        if not bucket:
            lines.extend(["_empty_", ""])
            continue
        lines.extend(
            [
                "| ID | Title | Owner | Branch | Updated |",
                "| :--- | :--- | :--- | :--- | :--- |",
            ]
        )
        for record in bucket:
            lines.append(
                "| {id} | {title} | {owner} | {branch} | {updated} |".format(
                    id=_escape_cell(record.get("id", "")),
                    title=_escape_cell(record.get("title", "")),
                    owner=_escape_cell(record.get("owner", "")) or "-",
                    branch=_escape_cell(record.get("branch", "")) or "-",
                    updated=_escape_cell(record.get("updated", "")) or "-",
                )
            )
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def render_json(
    records: Iterable[Record],
    columns: Sequence[str],
    *,
    timestamp: datetime,
) -> str:
    grouped = _grouped(records, columns)
    payload = {
        "generated": timestamp.strftime("%Y-%m-%dT%H:%M:%S"),
        "generator": "kahnban",
        "columns": [
            {
                "name": column,
                "count": len(grouped.get(column, [])),
                "tickets": [
                    {field: record.get(field, "") for field in FIELDS}
                    for record in grouped.get(column, [])
                ],
            }
            for column in columns
        ],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def write(
    plans_dir: Path,
    records: Iterable[Record],
    columns: Sequence[str],
    *,
    timestamp: datetime,
    project_name: str = "",
) -> list[Path]:
    """Write both projections; returns the paths written, in commit order."""
    materialized = list(records)
    plans_dir.mkdir(parents=True, exist_ok=True)
    markdown_path = plans_dir / "STATUS.md"
    json_path = plans_dir / "status.json"
    markdown_path.write_text(
        render_markdown(
            materialized, columns, timestamp=timestamp, project_name=project_name
        ),
        encoding="utf-8",
        newline="\n",
    )
    json_path.write_text(
        render_json(materialized, columns, timestamp=timestamp),
        encoding="utf-8",
        newline="\n",
    )
    return [markdown_path, json_path]
